// <auto-generated />
using System;
using ContactsManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908214230_Reset_Database")]
    partial class Reset_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactsManager.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("6e3be723-13e2-4068-b392-d9353ed41f6d"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = new Guid("fdde1f72-2a86-4a39-9ecc-846d840b91b9"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("13c250b3-2af6-40a9-9616-6e5abf1ea2a9"),
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryId = new Guid("969874c5-a77d-4158-b033-605ff940d04e"),
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("d67524d3-bf47-4f48-aef1-e20bbe3f0443"),
                            CountryName = "Ireland"
                        });
                });

            modelBuilder.Entity("ContactsManager.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsReceivingNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("PersonEmail")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PersonId");

                    b.ToTable("People", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("a2ef3bec-5e7f-40a7-ae9f-8adfba33e515"),
                            Address = "681 Sutherland Road",
                            CountryId = new Guid("6e3be723-13e2-4068-b392-d9353ed41f6d"),
                            DateOfBirth = new DateTime(2022, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "alukesch0@networksolutions.com",
                            PersonName = "Alfy"
                        },
                        new
                        {
                            PersonId = new Guid("f87d9a0d-dc9b-4751-9d0a-274bd26c1acb"),
                            Address = "0 Springs Hill",
                            CountryId = new Guid("13c250b3-2af6-40a9-9616-6e5abf1ea2a9"),
                            DateOfBirth = new DateTime(2010, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "kcraft1@dagondesign.com",
                            PersonName = "Kevyb"
                        },
                        new
                        {
                            PersonId = new Guid("254d8111-bf36-422c-a601-910d8cd3b7bd"),
                            Address = "677 Nelson Junction",
                            CountryId = new Guid("d67524d3-bf47-4f48-aef1-e20bbe3f0443"),
                            DateOfBirth = new DateTime(2004, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = true,
                            PersonEmail = "sespinha2@auda.org.au",
                            PersonName = "Sayre"
                        },
                        new
                        {
                            PersonId = new Guid("f530dd6d-175c-4c1c-8574-a2bbbae1fc2d"),
                            Address = "135 Clove Crossing",
                            CountryId = new Guid("969874c5-a77d-4158-b033-605ff940d04e"),
                            DateOfBirth = new DateTime(1992, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "bferrolli3@tiny.cc",
                            PersonName = "Britt"
                        },
                        new
                        {
                            PersonId = new Guid("96d243ca-e71a-464c-8f7a-89d81dc60c2b"),
                            Address = "9 Dakota Place",
                            CountryId = new Guid("969874c5-a77d-4158-b033-605ff940d04e"),
                            DateOfBirth = new DateTime(1987, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsReceivingNewsLetters = true,
                            PersonEmail = "agarlee4@yolasite.com",
                            PersonName = "Allyn"
                        },
                        new
                        {
                            PersonId = new Guid("34df3927-b48d-46d0-b515-58429145006f"),
                            Address = "53019 Daystar Plaza",
                            CountryId = new Guid("d67524d3-bf47-4f48-aef1-e20bbe3f0443"),
                            DateOfBirth = new DateTime(1980, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "dslimm5@miitbeian.gov.cn",
                            PersonName = "Demetris"
                        },
                        new
                        {
                            PersonId = new Guid("0eae4fe4-e774-4679-93d2-1da948d25dcc"),
                            Address = "96 Welch Street",
                            CountryId = new Guid("fdde1f72-2a86-4a39-9ecc-846d840b91b9"),
                            DateOfBirth = new DateTime(2003, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "hmora6@google.ru",
                            PersonName = "Hattie"
                        },
                        new
                        {
                            PersonId = new Guid("10b999ce-d7cd-48ed-a795-4bfe2b9c47d3"),
                            Address = "802 Melody Alley",
                            CountryId = new Guid("969874c5-a77d-4158-b033-605ff940d04e"),
                            DateOfBirth = new DateTime(1990, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "lcrittal7@dmoz.org",
                            PersonName = "Lindsy"
                        },
                        new
                        {
                            PersonId = new Guid("14c014a7-27ea-42b7-914d-5b6a8c827660"),
                            Address = "09 Dwight Point",
                            CountryId = new Guid("6e3be723-13e2-4068-b392-d9353ed41f6d"),
                            DateOfBirth = new DateTime(2002, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = false,
                            PersonEmail = "jpodbury8@usatoday.com",
                            PersonName = "Jeffry"
                        },
                        new
                        {
                            PersonId = new Guid("ccf78aad-0832-480e-8009-1190ae9f0445"),
                            Address = "418 Veith Junction",
                            CountryId = new Guid("fdde1f72-2a86-4a39-9ecc-846d840b91b9"),
                            DateOfBirth = new DateTime(1997, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsReceivingNewsLetters = true,
                            PersonEmail = "cmatuschek9@microsoft.com",
                            PersonName = "Chaim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
